ServerEvents.recipes(event => {
  event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 400)
    .requireEnergy(250000)
    .requireItem("kubejs:supreme_ingot_block", "input1")
    .requireItem("simplyswords:tampered_remnant", "input2")
    .produceItem("kubejs:rift_stabilizer", "output")

  event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 100)
    .requireEnergy(15000)
    .requireItem("angeloshammers:netherite_hammer", "input1")
    .requireItem("kubejs:supreme_ingot_block", "input2")
    .produceItem("kubejs:supreme_hammer", "output")

  event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 100)
    .requireEnergy(15000)
    .requireItem("advancednetherite:netherite_diamond_pickaxe", "input1")
    .requireItem("kubejs:supreme_ingot_block", "input2")
    .produceItem("kubejs:supreme_destruction", "output")

  event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 100)
    .requireEnergy(15000)
    .requireItem("advancednetherite:netherite_diamond_axe", "input1")
    .requireItem("kubejs:supreme_ingot_block", "input2")
    .produceItem("born_in_chaos_v1:supreme_measure", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 100)
    .requireEnergy(25000)
    .requireItem("chisel:large_tile/lapis_block", "input1")
    .requireItem("kubejs:saturated_remnant", "input2")
    .produceItem("chancecubes:chance_cube", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 200)
    .requireEnergy(75000)
    .requireItem("supplementaries:jar", "input1")
    .requireItem("simplyswords:empowered_remnant", "input2")
    .produceItem("simplyswords:contained_remnant", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 200)
    .requireEnergy(75000)
    .requireItem("supplementaries:jar", "input1")
    .requireItem("kubejs:saturated_remnant", "input2")
    .produceItem("simplyswords:tampered_remnant", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 400)
    .requireEnergy(500000)
    .requireItem("minecraft:carved_pumpkin", "input1")
    .requireItem("kubejs:big_bang_remnant_pieces", "input2")
    .produceItem("operation_starcleave:netherite_pumpkin", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 400)
    .requireEnergy(1000000)
    .requireItem("biomesoplenty:rose", "input1")
    .requireItem("kubejs:big_bang_remnant_pieces", "input2")
    .produceItem("kubejs:supreme_matter", "output")

 event.recipes.custommachinery.custom_machine("custommachinery:matter_manipulator", 300)
    .requireEnergy(50000)
    .requireItem("2x simplyswords:empowered_remnant", "input1")
    .requireItem("born_in_chaos_v1:transmuting_elixir", "input2")
    .produceItem("2x kubejs:saturated_remnant", "output")
})