StartupEvents.registry('block', event => {
	event.create('supreme_ingot_block')
		.texture('driedflower:block/supreme_ingot_block')
		.soundType('metal')
		.hardness(25.0)
		.resistance(1200.0)
		.requiresTool(true)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_netherite_tool')
	event.create('rift_stabilizer')
		.texture('driedflower:block/rift_stabilizer')
		.glassSoundType()
		.resistance(50.0)
		.requiresTool(true)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_netherite_tool')
})