StartupEvents.registry('item', event => {
// Supreme Items
	event.create('supreme_matter').texture('driedflower:item/supreme_matter')
		.maxStackSize(1)
		.fireResistant(true)
		.rarity('EPIC')
	event.create('supreme_ingot').texture('driedflower:item/supreme_ingot')
		.fireResistant(true)
	event.create('supreme_nugget').texture('driedflower:item/supreme_nugget')
		.fireResistant(true)
	event.create('supreme_rod').texture('driedflower:item/supreme_rod')
		.fireResistant(true)
// Supreme Destructions
	event.create('supreme_destruction', 'paxel').texture('driedflower:item/supreme_destruction')
		.tier('netherite')
		.fireResistant(true)
		.tag('minecraft:pickaxes')
		.tag('advancednetherite:tier/tool/netherite_diamond') 
		.tag('c:tools')
		.tag('c:tools/mining_tool')
		.tag('c:tools/mining_tools')
		.tag('c:enchantables')
		.tag('minecraft:enchantable/mining')
		.tag('minecraft:enchantable/durability')
	event.create('supreme_hammer', 'pickaxe').texture('driedflower:item/supreme_hammer')
		.tier('netherite')
		.fireResistant(true)
		.tag('minecraft:pickaxes')
		.tag('advancednetherite:tier/tool/netherite_diamond') 
		.tag('c:tools')
		.tag('c:tools/mining_tool')
		.tag('c:tools/mining_tools')
		.tag('c:enchantables')
		.tag('minecraft:enchantable/mining')
		.tag('minecraft:enchantable/durability')
// Stars
	event.create('star').texture('driedflower:item/star')
		.rarity('EPIC')
		.maxStackSize(16)
		.fireResistant(true)
	event.create('star_shards').texture('driedflower:item/star_shards')
		.rarity('EPIC')
		.maxStackSize(32)
		.fireResistant(true)
// Infuser Books
	event.create('enchanting_infuser_book').texture('driedflower:item/enchanting_infuser_book')
		.rarity('UNCOMMON')
		.maxStackSize(1)
	event.create('advanced_enchanting_infuser_book').texture('driedflower:item/advanced_enchanting_infuser_book')
		.rarity('RARE')
		.maxStackSize(1)
		.fireResistant(true)
// Moons Signs
	event.create('empty_moon_sign').texture('driedflower:item/empty_moon_sign')
		.maxStackSize(8)
	event.create('blood_moon_sign').texture('driedflower:item/blood_moon_sign')
		.fireResistant(true)
		.rarity('UNCOMMON')
		.maxStackSize(1)
	event.create('super_blood_moon_sign').texture('driedflower:item/super_blood_moon_sign')
		.rarity('RARE')
		.fireResistant(true)
		.maxStackSize(1)
	event.create('blue_moon_sign').texture('driedflower:item/blue_moon_sign')
		.fireResistant(true)
		.rarity('UNCOMMON')
		.maxStackSize(1)
	event.create('super_blue_moon_sign').texture('driedflower:item/super_blue_moon_sign')
		.rarity('RARE')
		.fireResistant(true)
		.maxStackSize(1)
	event.create('harvest_moon_sign').texture('driedflower:item/harvest_moon_sign')
		.fireResistant(true)
		.rarity('UNCOMMON')
		.maxStackSize(1)
	event.create('super_harvest_moon_sign').texture('driedflower:item/super_harvest_moon_sign')
		.rarity('RARE')
		.fireResistant(true)
		.maxStackSize(1)
	event.create('super_moon_sign').texture('driedflower:item/super_moon_sign')
		.fireResistant(true)
		.rarity('UNCOMMON')
		.maxStackSize(1)
// Food
	event.create('star_bucket').texture('driedflower:item/star_bucket')
		.rarity('RARE')
		.maxStackSize(1)
		.fireResistant(true)
		.unstackable()
		.food(food => {
			food.alwaysEdible(true)
			food.nutrition(10)
			food.saturation(0.6)
			food.eatSeconds(3)
		})
	event.create('supreme_food_bucket').texture('driedflower:item/supreme_food_bucket')
		.rarity('EPIC')
		.maxStackSize(1)
		.fireResistant(true)
		.unstackable()
		.food(food => {
			food.alwaysEdible()
			food.nutrition(40)
			food.saturation(1)
			food.eatSeconds(7)
		})
// Book and Quill
	event.create('coal_stub').texture('driedflower:item/coal_stub')
	event.create('coal_pen').texture('driedflower:item/coal_pen')
// Remnants
	event.create('ghostly_remnant').texture('driedflower:item/ghostly_remnant')
	event.create('saturated_remnant').texture('driedflower:item/saturated_remnant')
		.rarity('EPIC')
		.maxStackSize(16)
	event.create('big_bang_remnant').texture('driedflower:item/big_bang_remnant')
		.maxStackSize(1)
		.rarity('EPIC')
	event.create('big_bang_remnant_pieces').texture('driedflower:item/big_bang_remnant_pieces')
		.maxStackSize(4)
		.rarity('EPIC')
	event.create('supreme_essence').texture('driedflower:item/supreme_essence')
		.rarity('EPIC')
		.maxStackSize(1)
// Boss Lootbags
	event.create('sir_pumpkinhead_lootbag').texture('driedflower:item/sir_pumpkinhead_lootbag')
		.maxStackSize(1)
		.rarity('UNCOMMON')
	event.create('lord_pumpkinhead_lootbag').texture('driedflower:item/lord_pumpkinhead_lootbag')
		.maxStackSize(1)
		.rarity('RARE')
// Mob Grinding Utils Upgrades
	event.create('blank_upgrade').texture('driedflower:item/blank_upgrade')
	event.create('blank_height_upgrade').texture('driedflower:item/blank_height_upgrade')
	event.create('blank_width_upgrade').texture('driedflower:item/blank_width_upgrade')
	event.create('blank_distance_upgrade').texture('driedflower:item/blank_distance_upgrade')
// Others
	event.create('dark_metal_frame').texture('driedflower:item/dark_metal_frame')
	event.create('ender_eye_on_a_stick').texture('driedflower:item/ender_eye_on_a_stick')
		.maxStackSize(1)
	event.create('incomplete_oil_scanner').texture('driedflower:item/incomplete_oil_scanner')
		.maxStackSize(1)
	event.create('watered_sapling').texture('driedflower:item/watered_sapling')
		.maxStackSize(1)
});